### PR TITLE
Include extra metadata in queries and flatten directory

### PR DESCRIPTION
**Pull request by nicholsn**
This PR addresses #4 to include a query type, model, and component tag in queries. It also removes the arbitrary nidm experiment, workflow, results directories in favor of metadata tags as queries don't necessarily fall cleanly into this directory structure.

### CODE REVIEW

**Comment by vsoch** [comment]
hey I'll need to integrate this into the nidm-api before doing the merge, and a few quick questions!
- Can a model be of multiple types? So for example, instead of just "results" it may be a list like ["results","workflow"] ?

Are the "model" types from some standard terminology? It seems sort of general.

**Comment by nicholsn** [comment]
sounds good and sure, a query could cross more than one model. Currently I'm just making up the model types, but ideally these would be registered with a version, etc. - probably in the nidm repo

**Comment by vsoch** [comment]
How would the creator of the query know what version to designate?

**Comment by nicholsn** [comment]
if they were basing the query of a released version of a model, like nidm
results 1.1

**Comment by vsoch** [comment]
@nicholsn  could you give me definitions (examples/choices) for each of:
- format
- model
- component

for guiding the user in the interface, and so I can add to documentation?

**Comment by nicholsn** [comment]
Sure, this'll change but will work for the time being:

format: the type of sparql query - one of [SELECT, CONSTRUCT, ASK, UPDATE]
model: name of the object model being queried - one of [fMRI Results,
Freesurfer, General]
component: name of the nidm component the query belongs to - one of [PROV,
Results, Experiment, Workflow, Dataset Description, General]

**Comment by vsoch** [comment]
Awesome thanks! I just added to the docs:

http://nidm-api.readthedocs.org/en/latest/development.html#fields

**Pull request merged**
